package open.mind.its.recruitement.application.companymanagment;

import open.mind.its.recruitement.application.companymanagment.ENTITIES.CurrencyCountry;
import open.mind.its.recruitement.application.companymanagment.REPO.CurrencyCountryRepo;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

	//@Bean
	CommandLineRunner commandLineRunner(CurrencyCountryRepo currencyCountryRepo){
		return args -> {
			Map<String, String> countryCurrencyISOMap = new HashMap<>();

			// Add country-ISO currency pairs to the HashMap
			countryCurrencyISOMap.put("Afghanistan", "AFN");
			countryCurrencyISOMap.put("Akrotiri and Dhekelia (UK)", "EUR");
			countryCurrencyISOMap.put("Aland Islands (Finland)", "EUR");
			countryCurrencyISOMap.put("Albania", "ALL");
			countryCurrencyISOMap.put("Algeria", "DZD");
			countryCurrencyISOMap.put("American Samoa (USA)", "USD");
			countryCurrencyISOMap.put("Andorra", "EUR");
			countryCurrencyISOMap.put("Angola", "AOA");
			countryCurrencyISOMap.put("Anguilla (UK)", "XCD");
			countryCurrencyISOMap.put("Antigua and Barbuda", "XCD");
			countryCurrencyISOMap.put("Argentina", "ARS");
			countryCurrencyISOMap.put("Armenia", "AMD");
			countryCurrencyISOMap.put("Aruba (Netherlands)", "AWG");
			countryCurrencyISOMap.put("Ascension Island (UK)", "SHP");
			countryCurrencyISOMap.put("Australia", "AUD");
			countryCurrencyISOMap.put("Austria", "EUR");
			countryCurrencyISOMap.put("Azerbaijan", "AZN");
			countryCurrencyISOMap.put("Bahamas", "BSD");
			countryCurrencyISOMap.put("Bahrain", "BHD");
			countryCurrencyISOMap.put("Bangladesh", "BDT");
			countryCurrencyISOMap.put("Barbados", "BBD");
			countryCurrencyISOMap.put("Belarus", "BYN");
			countryCurrencyISOMap.put("Belgium", "EUR");
			countryCurrencyISOMap.put("Belize", "BZD");
			countryCurrencyISOMap.put("Benin", "XOF");
			countryCurrencyISOMap.put("Bermuda (UK)", "BMD");
			countryCurrencyISOMap.put("Bhutan", "BTN");
			countryCurrencyISOMap.put("Bolivia", "BOB");
			countryCurrencyISOMap.put("Bonaire (Netherlands)", "USD");
			countryCurrencyISOMap.put("Bosnia and Herzegovina", "BAM");
			countryCurrencyISOMap.put("Botswana", "BWP");
			countryCurrencyISOMap.put("Brazil", "BRL");
			countryCurrencyISOMap.put("British Indian Ocean Territory (UK)", "USD");
			countryCurrencyISOMap.put("British Virgin Islands (UK)", "USD");
			countryCurrencyISOMap.put("Brunei", "BND");
			countryCurrencyISOMap.put("Bulgaria", "BGN");
			countryCurrencyISOMap.put("Burkina Faso", "XOF");
			countryCurrencyISOMap.put("Burundi", "BIF");
			countryCurrencyISOMap.put("Cabo Verde", "CVE");
			countryCurrencyISOMap.put("Cambodia", "KHR");
			countryCurrencyISOMap.put("Cameroon", "XAF");
			countryCurrencyISOMap.put("Canada", "CAD");
			countryCurrencyISOMap.put("Caribbean Netherlands (Netherlands)", "USD");
			countryCurrencyISOMap.put("Cayman Islands (UK)", "KYD");
			countryCurrencyISOMap.put("Central African Republic", "XAF");
			countryCurrencyISOMap.put("Chad", "XAF");
			countryCurrencyISOMap.put("Chatham Islands (New Zealand)", "NZD");
			countryCurrencyISOMap.put("Chile", "CLP");
			countryCurrencyISOMap.put("China", "CNY");
			countryCurrencyISOMap.put("Christmas Island (Australia)", "AUD");
			countryCurrencyISOMap.put("Cocos (Keeling) Islands (Australia)", "AUD");
			countryCurrencyISOMap.put("Colombia", "COP");
			countryCurrencyISOMap.put("Comoros", "KMF");
			countryCurrencyISOMap.put("Congo, Democratic Republic of the", "CDF");
			countryCurrencyISOMap.put("Congo, Republic of the", "XAF");
			countryCurrencyISOMap.put("Cook Islands (New Zealand)", "none");
			countryCurrencyISOMap.put("Costa Rica", "CRC");
			countryCurrencyISOMap.put("Cote d'Ivoire", "XOF");
			countryCurrencyISOMap.put("Croatia", "EUR");
			countryCurrencyISOMap.put("Cuba", "CUP");
			countryCurrencyISOMap.put("Curacao (Netherlands)", "ANG");
			countryCurrencyISOMap.put("Cyprus", "EUR");
			countryCurrencyISOMap.put("Czechia", "CZK");
			countryCurrencyISOMap.put("Denmark", "DKK");
			countryCurrencyISOMap.put("Djibouti", "DJF");
			countryCurrencyISOMap.put("Dominica", "XCD");
			countryCurrencyISOMap.put("Dominican Republic", "DOP");
			countryCurrencyISOMap.put("Ecuador", "USD");
			countryCurrencyISOMap.put("Egypt", "EGP");
			countryCurrencyISOMap.put("El Salvador", "USD");
			countryCurrencyISOMap.put("Equatorial Guinea", "XAF");
			countryCurrencyISOMap.put("Eritrea", "ERN");
			countryCurrencyISOMap.put("Estonia", "EUR");
			countryCurrencyISOMap.put("Eswatini", "SZL");
			countryCurrencyISOMap.put("Ethiopia", "ETB");
			countryCurrencyISOMap.put("Falkland Islands (UK)", "FKP");
			countryCurrencyISOMap.put("Faroe Islands (Denmark)", "none");
			countryCurrencyISOMap.put("Fiji", "FJD");
			countryCurrencyISOMap.put("Finland", "EUR");
			countryCurrencyISOMap.put("France", "EUR");
			countryCurrencyISOMap.put("French Guiana (France)", "EUR");
			countryCurrencyISOMap.put("French Polynesia (France)", "XPF");
			countryCurrencyISOMap.put("Gabon", "XAF");
			countryCurrencyISOMap.put("Gambia", "GMD");
			countryCurrencyISOMap.put("Georgia", "GEL");
			countryCurrencyISOMap.put("Germany", "EUR");
			countryCurrencyISOMap.put("Ghana", "GHS");
			countryCurrencyISOMap.put("Gibraltar (UK)", "GIP");
			countryCurrencyISOMap.put("Greece", "EUR");
			countryCurrencyISOMap.put("Greenland (Denmark)", "DKK");
			countryCurrencyISOMap.put("Grenada", "XCD");
			countryCurrencyISOMap.put("Guadeloupe (France)", "EUR");
			countryCurrencyISOMap.put("Guam (USA)", "USD");
			countryCurrencyISOMap.put("Guatemala", "GTQ");
			countryCurrencyISOMap.put("Guernsey (UK)", "GGP");
			countryCurrencyISOMap.put("Guinea", "GNF");
			countryCurrencyISOMap.put("Guinea-Bissau", "XOF");
			countryCurrencyISOMap.put("Guyana", "GYD");
			countryCurrencyISOMap.put("Haiti", "HTG");
			countryCurrencyISOMap.put("Honduras", "HNL");
			countryCurrencyISOMap.put("Hong Kong (China)", "HKD");
			countryCurrencyISOMap.put("Hungary", "HUF");
			countryCurrencyISOMap.put("Iceland", "ISK");
			countryCurrencyISOMap.put("India", "INR");
			countryCurrencyISOMap.put("Indonesia", "IDR");
			countryCurrencyISOMap.put("International Monetary Fund (IMF)", "XDR");
			countryCurrencyISOMap.put("Iran", "IRR");
			countryCurrencyISOMap.put("Iraq", "IQD");
			countryCurrencyISOMap.put("Ireland", "EUR");
			countryCurrencyISOMap.put("Isle of Man (UK)", "IMP");
			countryCurrencyISOMap.put("Italy", "EUR");
			countryCurrencyISOMap.put("Jamaica", "JMD");
			countryCurrencyISOMap.put("Japan", "JPY");
			countryCurrencyISOMap.put("Jersey (UK)", "JEP");
			countryCurrencyISOMap.put("Jordan", "JOD");
			countryCurrencyISOMap.put("Kazakhstan", "KZT");
			countryCurrencyISOMap.put("Kenya", "KES");
			countryCurrencyISOMap.put("Kiribati", "AUD");
			countryCurrencyISOMap.put("Kosovo", "EUR");
			countryCurrencyISOMap.put("Kuwait", "KWD");
			countryCurrencyISOMap.put("Kyrgyzstan", "KGS");
			countryCurrencyISOMap.put("Laos", "LAK");
			countryCurrencyISOMap.put("Latvia", "EUR");
			countryCurrencyISOMap.put("Lebanon", "LBP");
			countryCurrencyISOMap.put("Lesotho", "LSL");
			countryCurrencyISOMap.put("Liberia", "LRD");
			countryCurrencyISOMap.put("Libya", "LYD");
			countryCurrencyISOMap.put("Liechtenstein", "CHF");
			countryCurrencyISOMap.put("Lithuania", "EUR");
			countryCurrencyISOMap.put("Luxembourg", "EUR");
			countryCurrencyISOMap.put("Macau (China)", "MOP");
			countryCurrencyISOMap.put("Madagascar", "MGA");
			countryCurrencyISOMap.put("Malawi", "MWK");
			countryCurrencyISOMap.put("Malaysia", "MYR");
			countryCurrencyISOMap.put("Maldives", "MVR");
			countryCurrencyISOMap.put("Mali", "XOF");
			countryCurrencyISOMap.put("Malta", "EUR");
			countryCurrencyISOMap.put("Marshall Islands", "USD");
			countryCurrencyISOMap.put("Martinique (France)", "EUR");
			countryCurrencyISOMap.put("Mauritania", "MRU");
			countryCurrencyISOMap.put("Mauritius", "MUR");
			countryCurrencyISOMap.put("Mayotte (France)", "EUR");
			countryCurrencyISOMap.put("Mexico", "MXN");
			countryCurrencyISOMap.put("Micronesia", "USD");
			countryCurrencyISOMap.put("Moldova", "MDL");
			countryCurrencyISOMap.put("Monaco", "EUR");
			countryCurrencyISOMap.put("Mongolia", "MNT");
			countryCurrencyISOMap.put("Montenegro", "EUR");
			countryCurrencyISOMap.put("Montserrat (UK)", "XCD");
			countryCurrencyISOMap.put("Morocco", "MAD");
			countryCurrencyISOMap.put("Mozambique", "MZN");
			countryCurrencyISOMap.put("Myanmar", "MMK");
			countryCurrencyISOMap.put("Namibia", "NAD");
			countryCurrencyISOMap.put("Nauru", "AUD");
			countryCurrencyISOMap.put("Nepal", "NPR");
			countryCurrencyISOMap.put("Netherlands", "EUR");
			countryCurrencyISOMap.put("New Caledonia (France)", "XPF");
			countryCurrencyISOMap.put("New Zealand", "NZD");
			countryCurrencyISOMap.put("Nicaragua", "NIO");
			countryCurrencyISOMap.put("Niger", "XOF");
			countryCurrencyISOMap.put("Nigeria", "NGN");
			countryCurrencyISOMap.put("Niue (New Zealand)", "NZD");
			countryCurrencyISOMap.put("Norfolk Island (Australia)", "AUD");
			countryCurrencyISOMap.put("Northern Mariana Islands (USA)", "USD");
			countryCurrencyISOMap.put("North Korea", "KPW");
			countryCurrencyISOMap.put("North Macedonia", "MKD");
			countryCurrencyISOMap.put("Norway", "NOK");
			countryCurrencyISOMap.put("Oman", "OMR");
			countryCurrencyISOMap.put("Pakistan", "PKR");
			countryCurrencyISOMap.put("Palau", "USD");
			countryCurrencyISOMap.put("Palestine", "ILS");
			countryCurrencyISOMap.put("Panama", "USD");
			countryCurrencyISOMap.put("Papua New Guinea", "PGK");
			countryCurrencyISOMap.put("Paraguay", "PYG");
			countryCurrencyISOMap.put("Peru", "PEN");
			countryCurrencyISOMap.put("Philippines", "PHP");
			countryCurrencyISOMap.put("Pitcairn Islands (UK)", "NZD");
			countryCurrencyISOMap.put("Poland", "PLN");
			countryCurrencyISOMap.put("Portugal", "EUR");
			countryCurrencyISOMap.put("Puerto Rico (USA)", "USD");
			countryCurrencyISOMap.put("Qatar", "QAR");
			countryCurrencyISOMap.put("Reunion (France)", "EUR");
			countryCurrencyISOMap.put("Romania", "RON");
			countryCurrencyISOMap.put("Russia", "RUB");
			countryCurrencyISOMap.put("Rwanda", "RWF");
			countryCurrencyISOMap.put("Saba (Netherlands)", "USD");
			countryCurrencyISOMap.put("Saint Barthelemy (France)", "EUR");
			countryCurrencyISOMap.put("Saint Helena (UK)", "SHP");
			countryCurrencyISOMap.put("Saint Kitts and Nevis", "XCD");
			countryCurrencyISOMap.put("Saint Lucia", "XCD");
			countryCurrencyISOMap.put("Saint Martin (France)", "EUR");
			countryCurrencyISOMap.put("Saint Pierre and Miquelon (France)", "EUR");
			countryCurrencyISOMap.put("Saint Vincent and the Grenadines", "XCD");
			countryCurrencyISOMap.put("Samoa", "WST");
			countryCurrencyISOMap.put("San Marino", "EUR");
			countryCurrencyISOMap.put("Sao Tome and Principe", "STN");
			countryCurrencyISOMap.put("Saudi Arabia", "SAR");
			countryCurrencyISOMap.put("Senegal", "XOF");
			countryCurrencyISOMap.put("Serbia", "RSD");
			countryCurrencyISOMap.put("Seychelles", "SCR");
			countryCurrencyISOMap.put("Sierra Leone", "SLE");
			countryCurrencyISOMap.put("Singapore", "SGD");
			countryCurrencyISOMap.put("Sint Eustatius (Netherlands)", "USD");
			countryCurrencyISOMap.put("Sint Maarten (Netherlands)", "ANG");
			countryCurrencyISOMap.put("Slovakia", "EUR");
			countryCurrencyISOMap.put("Slovenia", "EUR");
			countryCurrencyISOMap.put("Solomon Islands", "SBD");
			countryCurrencyISOMap.put("Somalia", "SOS");
			countryCurrencyISOMap.put("South Africa", "ZAR");
			countryCurrencyISOMap.put("South Georgia Island (UK)", "GBP");
			countryCurrencyISOMap.put("South Korea", "KRW");
			countryCurrencyISOMap.put("South Sudan", "SSP");
			countryCurrencyISOMap.put("Spain", "EUR");
			countryCurrencyISOMap.put("Sri Lanka", "LKR");
			countryCurrencyISOMap.put("Sudan", "SDG");
			countryCurrencyISOMap.put("Suriname", "SRD");
			countryCurrencyISOMap.put("Svalbard and Jan Mayen (Norway)", "NOK");
			countryCurrencyISOMap.put("Sweden", "SEK");
			countryCurrencyISOMap.put("Switzerland", "CHF");
			countryCurrencyISOMap.put("Syria", "SYP");
			countryCurrencyISOMap.put("Taiwan", "TWD");
			countryCurrencyISOMap.put("Tajikistan", "TJS");
			countryCurrencyISOMap.put("Tanzania", "TZS");
			countryCurrencyISOMap.put("Thailand", "THB");
			countryCurrencyISOMap.put("Timor-Leste", "USD");
			countryCurrencyISOMap.put("Togo", "XOF");
			countryCurrencyISOMap.put("Tokelau (New Zealand)", "NZD");
			countryCurrencyISOMap.put("Tonga", "TOP");
			countryCurrencyISOMap.put("Trinidad and Tobago", "TTD");
			countryCurrencyISOMap.put("Tristan da Cunha (UK)", "GBP");
			countryCurrencyISOMap.put("Tunisia", "TND");
			countryCurrencyISOMap.put("Turkey", "TRY");
			countryCurrencyISOMap.put("Turkmenistan", "TMT");
			countryCurrencyISOMap.put("Turks and Caicos Islands (UK)", "USD");
			countryCurrencyISOMap.put("Tuvalu", "AUD");
			countryCurrencyISOMap.put("Uganda", "UGX");
			countryCurrencyISOMap.put("Ukraine", "UAH");
			countryCurrencyISOMap.put("United Arab Emirates", "AED");
			countryCurrencyISOMap.put("United Kingdom", "GBP");
			countryCurrencyISOMap.put("United States of America", "USD");
			countryCurrencyISOMap.put("Uruguay", "UYU");
			countryCurrencyISOMap.put("US Virgin Islands (USA)", "USD");
			countryCurrencyISOMap.put("Uzbekistan", "UZS");
			countryCurrencyISOMap.put("Vanuatu", "VUV");
			countryCurrencyISOMap.put("Vatican City (Holy See)", "EUR");
			countryCurrencyISOMap.put("Venezuela", "VES");
			countryCurrencyISOMap.put("Vietnam", "VND");
			countryCurrencyISOMap.put("Wake Island (USA)", "USD");
			countryCurrencyISOMap.put("Wallis and Futuna (France)", "XPF");
			countryCurrencyISOMap.put("Yemen", "YER");
			countryCurrencyISOMap.put("Zambia", "ZMW");
			countryCurrencyISOMap.put("Zimbabwe", "USD");
			for (Map.Entry<String, String> entry : countryCurrencyISOMap.entrySet()) {
				currencyCountryRepo.save(
						CurrencyCountry.builder()
								.id(UUID.randomUUID().toString())
								.country(entry.getKey())
								.currency(entry.getValue())
								.build()
				);
			}


		};
	}

}
